// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'8b6804936a1e30c04db5c4b625cda89cb765461ce9472a17b53ab85579d7c3d0'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Anime: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly coverImage: CodecTypes['pg/text@1']['output'] | null;
      readonly bannerImage: CodecTypes['pg/text@1']['output'] | null;
      readonly year: CodecTypes['pg/int4@1']['output'] | null;
      readonly episodes: CodecTypes['pg/int4@1']['output'] | null;
      readonly status: 'ONGOING' | 'FINISHED' | 'ANNOUNCED';
      readonly type: 'TV' | 'MOVIE' | 'OVA' | 'ONA' | 'SPECIAL';
      readonly rating: CodecTypes['pg/float8@1']['output'] | null;
    };
    readonly AnimeCharacter: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly characterId: CodecTypes['pg/int4@1']['output'];
    };
    readonly AnimeGenre: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly genreId: CodecTypes['pg/int4@1']['output'];
    };
    readonly AnimeStudio: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly studioId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Character: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly role: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Genre: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Screenshot: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'];
      readonly animeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Studio: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Anime: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly coverImage: CodecTypes['pg/text@1']['input'] | null;
      readonly bannerImage: CodecTypes['pg/text@1']['input'] | null;
      readonly year: CodecTypes['pg/int4@1']['input'] | null;
      readonly episodes: CodecTypes['pg/int4@1']['input'] | null;
      readonly status: 'ONGOING' | 'FINISHED' | 'ANNOUNCED';
      readonly type: 'TV' | 'MOVIE' | 'OVA' | 'ONA' | 'SPECIAL';
      readonly rating: CodecTypes['pg/float8@1']['input'] | null;
    };
    readonly AnimeCharacter: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly characterId: CodecTypes['pg/int4@1']['input'];
    };
    readonly AnimeGenre: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly genreId: CodecTypes['pg/int4@1']['input'];
    };
    readonly AnimeStudio: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly studioId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Character: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly role: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Genre: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Screenshot: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'];
      readonly animeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Studio: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly anime: {
      readonly bannerImage: CodecTypes['pg/text@1']['output'] | null;
      readonly coverImage: CodecTypes['pg/text@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly episodes: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly rating: CodecTypes['pg/float8@1']['output'] | null;
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly status: 'ONGOING' | 'FINISHED' | 'ANNOUNCED';
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly type: 'TV' | 'MOVIE' | 'OVA' | 'ONA' | 'SPECIAL';
      readonly year: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly animeCharacter: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly characterId: CodecTypes['pg/int4@1']['output'];
    };
    readonly animeGenre: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly genreId: CodecTypes['pg/int4@1']['output'];
    };
    readonly animeStudio: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly studioId: CodecTypes['pg/int4@1']['output'];
    };
    readonly character: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly genre: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly screenshot: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'];
    };
    readonly studio: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly anime: {
      readonly bannerImage: CodecTypes['pg/text@1']['input'] | null;
      readonly coverImage: CodecTypes['pg/text@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly episodes: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly rating: CodecTypes['pg/float8@1']['input'] | null;
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly status: 'ONGOING' | 'FINISHED' | 'ANNOUNCED';
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly type: 'TV' | 'MOVIE' | 'OVA' | 'ONA' | 'SPECIAL';
      readonly year: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly animeCharacter: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly characterId: CodecTypes['pg/int4@1']['input'];
    };
    readonly animeGenre: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly genreId: CodecTypes['pg/int4@1']['input'];
    };
    readonly animeStudio: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly studioId: CodecTypes['pg/int4@1']['input'];
    };
    readonly character: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly genre: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly screenshot: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'];
    };
    readonly studio: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Anime = {
    id: CodecTypes['pg/int4@1']['output'];
    title: CodecTypes['pg/text@1']['output'];
    slug: CodecTypes['pg/text@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    coverImage: CodecTypes['pg/text@1']['output'] | null;
    bannerImage: CodecTypes['pg/text@1']['output'] | null;
    year: CodecTypes['pg/int4@1']['output'] | null;
    episodes: CodecTypes['pg/int4@1']['output'] | null;
    status: 'ONGOING' | 'FINISHED' | 'ANNOUNCED';
    type: 'TV' | 'MOVIE' | 'OVA' | 'ONA' | 'SPECIAL';
    rating: CodecTypes['pg/float8@1']['output'] | null;
    characters: public_AnimeCharacter[];
    genres: public_AnimeGenre[];
    screenshots: public_Screenshot[];
    studios: public_AnimeStudio[];
    readonly [RelationKeys]?: 'characters' | 'genres' | 'screenshots' | 'studios';
  };
  export type public_Genre = {
    id: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    animeGenres: public_AnimeGenre[];
    readonly [RelationKeys]?: 'animeGenres';
  };
  export type public_AnimeGenre = {
    animeId: CodecTypes['pg/int4@1']['output'];
    genreId: CodecTypes['pg/int4@1']['output'];
    anime: public_Anime;
    genre: public_Genre;
    readonly [RelationKeys]?: 'anime' | 'genre';
  };
  export type public_Screenshot = {
    id: CodecTypes['pg/int4@1']['output'];
    imageUrl: CodecTypes['pg/text@1']['output'];
    animeId: CodecTypes['pg/int4@1']['output'];
    anime: public_Anime;
    readonly [RelationKeys]?: 'anime';
  };
  export type public_Character = {
    id: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    imageUrl: CodecTypes['pg/text@1']['output'] | null;
    role: CodecTypes['pg/text@1']['output'] | null;
    animeCharacters: public_AnimeCharacter[];
    readonly [RelationKeys]?: 'animeCharacters';
  };
  export type public_AnimeCharacter = {
    animeId: CodecTypes['pg/int4@1']['output'];
    characterId: CodecTypes['pg/int4@1']['output'];
    anime: public_Anime;
    character: public_Character;
    readonly [RelationKeys]?: 'anime' | 'character';
  };
  export type public_Studio = {
    id: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    animeStudios: public_AnimeStudio[];
    readonly [RelationKeys]?: 'animeStudios';
  };
  export type public_AnimeStudio = {
    animeId: CodecTypes['pg/int4@1']['output'];
    studioId: CodecTypes['pg/int4@1']['output'];
    anime: public_Anime;
    studio: public_Studio;
    readonly [RelationKeys]?: 'anime' | 'studio';
  };
}

export declare const models: {
  public: {
    Anime: Models.public_Anime;
    Genre: Models.public_Genre;
    AnimeGenre: Models.public_AnimeGenre;
    Screenshot: Models.public_Screenshot;
    Character: Models.public_Character;
    AnimeCharacter: Models.public_AnimeCharacter;
    Studio: Models.public_Studio;
    AnimeStudio: Models.public_AnimeStudio;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly anime: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly coverImage: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly bannerImage: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly year: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly episodes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly animeCharacter: {
              columns: {
                readonly animeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly characterId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['animeId', 'characterId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'animeCharacter_animeId_idx_46bb9889';
                  readonly prefix: 'animeCharacter_animeId_idx';
                  readonly columns: readonly ['animeId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'animeCharacter_characterId_idx_2423fe9d';
                  readonly prefix: 'animeCharacter_characterId_idx';
                  readonly columns: readonly ['characterId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'animeCharacter';
                    readonly columns: readonly ['animeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'anime';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'animeCharacter';
                    readonly columns: readonly ['characterId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'character';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly animeGenre: {
              columns: {
                readonly animeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly genreId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['animeId', 'genreId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'animeGenre_animeId_idx_46bb9889';
                  readonly prefix: 'animeGenre_animeId_idx';
                  readonly columns: readonly ['animeId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'animeGenre_genreId_idx_8fce6a7b';
                  readonly prefix: 'animeGenre_genreId_idx';
                  readonly columns: readonly ['genreId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'animeGenre';
                    readonly columns: readonly ['animeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'anime';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'animeGenre';
                    readonly columns: readonly ['genreId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'genre';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly animeStudio: {
              columns: {
                readonly animeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly studioId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['animeId', 'studioId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'animeStudio_animeId_idx_46bb9889';
                  readonly prefix: 'animeStudio_animeId_idx';
                  readonly columns: readonly ['animeId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'animeStudio_studioId_idx_efc35ac7';
                  readonly prefix: 'animeStudio_studioId_idx';
                  readonly columns: readonly ['studioId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'animeStudio';
                    readonly columns: readonly ['animeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'anime';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'animeStudio';
                    readonly columns: readonly ['studioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'studio';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly character: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly imageUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly genre: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['name'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly screenshot: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly imageUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly animeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'screenshot_animeId_idx_46bb9889';
                  readonly prefix: 'screenshot_animeId_idx';
                  readonly columns: readonly ['animeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'screenshot';
                    readonly columns: readonly ['animeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'anime';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly studio: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['name'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly AnimeStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ONGOING', 'FINISHED', 'ANNOUNCED'];
            };
            readonly AnimeType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['TV', 'MOVIE', 'OVA', 'ONA', 'SPECIAL'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly anime: { readonly namespace: 'public' & NamespaceId; readonly model: 'Anime' };
    readonly genre: { readonly namespace: 'public' & NamespaceId; readonly model: 'Genre' };
    readonly animeGenre: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AnimeGenre';
    };
    readonly screenshot: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Screenshot';
    };
    readonly character: { readonly namespace: 'public' & NamespaceId; readonly model: 'Character' };
    readonly animeCharacter: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AnimeCharacter';
    };
    readonly studio: { readonly namespace: 'public' & NamespaceId; readonly model: 'Studio' };
    readonly animeStudio: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AnimeStudio';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Anime: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly coverImage: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly bannerImage: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly year: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly episodes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rating: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
            };
            readonly relations: {
              readonly characters: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AnimeCharacter';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['animeId'];
                };
              };
              readonly genres: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AnimeGenre';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['animeId'];
                };
              };
              readonly screenshots: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Screenshot';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['animeId'];
                };
              };
              readonly studios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AnimeStudio';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['animeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'anime';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly slug: { readonly column: 'slug' };
                readonly description: { readonly column: 'description' };
                readonly coverImage: { readonly column: 'coverImage' };
                readonly bannerImage: { readonly column: 'bannerImage' };
                readonly year: { readonly column: 'year' };
                readonly episodes: { readonly column: 'episodes' };
                readonly status: { readonly column: 'status' };
                readonly type: { readonly column: 'type' };
                readonly rating: { readonly column: 'rating' };
              };
            };
          };
          readonly AnimeCharacter: {
            readonly fields: {
              readonly animeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly characterId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly anime: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Anime';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['animeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly character: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Character';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['characterId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'animeCharacter';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly animeId: { readonly column: 'animeId' };
                readonly characterId: { readonly column: 'characterId' };
              };
            };
          };
          readonly AnimeGenre: {
            readonly fields: {
              readonly animeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly genreId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly anime: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Anime';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['animeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly genre: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Genre';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['genreId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'animeGenre';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly animeId: { readonly column: 'animeId' };
                readonly genreId: { readonly column: 'genreId' };
              };
            };
          };
          readonly AnimeStudio: {
            readonly fields: {
              readonly animeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly studioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly anime: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Anime';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['animeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly studio: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Studio';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'animeStudio';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly animeId: { readonly column: 'animeId' };
                readonly studioId: { readonly column: 'studioId' };
              };
            };
          };
          readonly Character: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly animeCharacters: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AnimeCharacter';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['characterId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'character';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly imageUrl: { readonly column: 'imageUrl' };
                readonly role: { readonly column: 'role' };
              };
            };
          };
          readonly Genre: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly animeGenres: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AnimeGenre';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['genreId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'genre';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Screenshot: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly imageUrl: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly animeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly anime: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Anime';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['animeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'screenshot';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly imageUrl: { readonly column: 'imageUrl' };
                readonly animeId: { readonly column: 'animeId' };
              };
            };
          };
          readonly Studio: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly animeStudios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AnimeStudio';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studioId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'studio';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
        };
        readonly enum: {
          readonly AnimeStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ONGOING'; readonly value: 'ONGOING' },
              { readonly name: 'FINISHED'; readonly value: 'FINISHED' },
              { readonly name: 'ANNOUNCED'; readonly value: 'ANNOUNCED' },
            ];
          };
          readonly AnimeType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'TV'; readonly value: 'TV' },
              { readonly name: 'MOVIE'; readonly value: 'MOVIE' },
              { readonly name: 'OVA'; readonly value: 'OVA' },
              { readonly name: 'ONA'; readonly value: 'ONA' },
              { readonly name: 'SPECIAL'; readonly value: 'SPECIAL' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
